config/routes.rb
MalhaLogistica::Application.routes.draw do
  resources :paths do
    collection do
      get :create_massive
    end
  end
  get 'figure(/:map_id/:begin_point/:end_point/:autonomy/:price)' => 'paths#figure'

  root 'paths#index'

end

app/models/path.rb
class Path < ActiveRecord::Base

	attr_accessor :intermadiate_points

	def self.massive_new(*params)
		p = params.map!(&:strip)
		new({local:p[0], begin_point:p[1], end_point:p[2], distance:p[3]})
	end
	class << self
		# map id, begin_point, end_point, autonomy (km/L), price (R$/L)
		def better(map_id, begin_point, end_point, autonomy, price)
			routes = Path.where(local:map_id)
			#routes = routes.as_json
			#routes = routes.to_a.map(&:serializable_hash)
			analyse_routes = Path.analyse_paths(routes.as_json)
			Path.mount_result(
				analyse_routes, 
				begin_point, 
				end_point, 
				autonomy, 
				price)
		end	

  	#TODO: improve performance (test logical in database to more speed)
  	def analyse_paths(arr_routes)
  		#arr_routes = arr_routes.as_json if arr_routes.is_a? String
			arr_routes.each{|i| 
				# to acept ActiveRecord_Relation
				i = i.serializable_hash if i.respond_to?(:serializable_hash)
				#TODO: No detect. It needs to be recursive and take all path possibles
				hs_sequel_path = arr_routes.detect{|n| i['end_point']==n['begin_point']}
				unless hs_sequel_path.nil?
					new_i = i.clone
					new_i['end_point'] = hs_sequel_path['end_point']
					new_i['distance'] = new_i['distance'].to_f+hs_sequel_path['distance'].to_f
					new_i['intermadiate_points'] = [hs_sequel_path['begin_point']]
					arr_routes << new_i
				end
			}
		end
		def mount_result(arr_routes, begin_point, end_point, autonomy, price)
			top = arr_routes.to_a.take_between_and_sort(begin_point, end_point).first
			{ 
				points: [top['begin_point'], top['end_point'], *top['intermadiate_points']].sort, 
				cost:Path.figure_cost(top['distance'], autonomy, price.to_f), distance:top['distance']
			}
  	end
  	# distance (Km)
  	# autonomy (Km/L)
  	# price (R$/L)
  	# figure: (distance/autonomy)*price
  	def figure_cost(distance, autonomy, price)
  		((distance.to_f/autonomy.to_f)*price.to_f)
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    @info_pattern = "Sampa, A, B, 10\r\nSampa, B, D, 15\r\nSampa, A, C, 20\r\nSampa, C, D, 30\r\nSampa, B, E, 50\r\nSampa, D, E, 30"
    @paths = Path.all
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  # POST /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to @path, notice: 'Path was successfully created.' }
        format.json { render action: 'show', status: :created, location: @path }
      else
        format.html { render action: 'new' }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_massive
    paths = []
    params[:massive_paths].split(/\r\n/).each do |line|
      paths << Path.massive_new(*line.split(','))
    end
    Path.import(paths)
    redirect_to({action: :index }, notice: "Paths was successfully created.")
  end

  # PATCH/PUT /paths/1
  # PATCH/PUT /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to @path, notice: 'Path was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1
  # DELETE /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
      format.html { redirect_to paths_url }
      format.json { head :no_content }
    end
  end

  # Ajax: get the best route
  def figure
    #@real, @cstime, @cutime, @stime, @utime, @total
    # Benchmark
    report = Benchmark.benchmark do |x|
      f = x.report("selecting map:"){ @routes = Path.where(local:params[:map_id]) }
      s = x.report("analysing routes:"){ @analyse_routes = Path.analyse_paths(@routes.as_json)}
      t = x.report("taking the best:"){ @top_result = Path.mount_result(@analyse_routes, params[:begin_point], params[:end_point], params[:autonomy], params[:price]) }
    end
    rows = {db_rows:@routes.size, analyse_rows:@analyse_routes.size}
    if params[:format] == 'json'
      render json: @top_result and return
    else
      render action: 'figure', locals: {top_result: @top_result, report:report, rows:rows} and return
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:local, :begin_point, :end_point, :distance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/layouts/_header.html.erb
<style>
body {
  padding-top: 20px;
  padding-bottom: 20px;
}
.navbar {
  margin-bottom: 20px;
}
</style>
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Malha Logística</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Start</a></li>
        <li><a href="http://about.me/alther" target="_blank">About author</a></li>
        <li><a href="https://gist.github.com/altherlex/60d880db939b9b0e6d85" target="_blank">About challenge</a></li>
        <li><a href="mailto:para.alves@gmail.com" target="_blank">Contact</a></li>
<!--        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
-->        
      </ul>
<!--      
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
        <li><a href="../navbar-static-top/">Static top</a></li>
        <li><a href="../navbar-fixed-top/">Fixed top</a></li>
      </ul>
-->      
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MalhaLogistica</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render "layouts/header" %>
		<%= yield %>
	</div>
</body>
</html>

app/views/paths/_benchmark.html.erb
<p>db rows loaded: <%=rows[:db_rows]%></p>
<p>analyzed lines: <%=rows[:analyse_rows]%></p>
<table class='table'>
<thead>
<tr>
  <th></th>
  <th>user (sec)</th>
  <th>system (sec)</th>
  <th>total (sec)</th>
  <th>real (sec)</th>
</tr>
</thead>
<tbody>
	<%report.each do |row|%>
	<tr>
		<td><%= row.label %></td>
		<td><%= row.cstime %></td>
		<td><%= row.stime %></td>
		<td><%= row.total %></td>
		<td><%= row.real %></td>
	</tr>
	<%end%>
</tbody>	
<tfoot>
	<tr>	
		<td>total:</td>
		<td><%=report.map(&:cstime).sum%></td>
		<td><%=report.map(&:stime).sum%></td>
		<td><%=report.map(&:total).sum%></td>
		<td><%=report.map(&:real).sum%></td>
	</tr>
</tfoot>	
</table>

app/views/paths/_form.html.erb
<%= form_for(@path) do |f| %>
  <% if @path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
      <% @path.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :begin_point %><br>
    <%= f.text_field :begin_point %>
  </div>
  <div class="field">
    <%= f.label :end_point %><br>
    <%= f.text_field :end_point %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing path</h1>

<%= render 'form' %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/figure.js.erb
$('#top_result').html('<%=top_result.inspect%>');
$('#benchmark').html("<%= escape_javascript(render(partial:'benchmark', locals:{report:report, rows:rows})).html_safe %>");

app/views/paths/index.html.erb
<%= link_to '+Add massive paths', "#", :onclick=>"go()" %>
<script>
function go(){
  if ($('#new_path').is(":visible"))
    $('#new_path').hide();  
  else
    $('#new_path').show();
}
</script>
<div class="panel panel-default" id="new_path" style='display:none'>
<div class="panel-body">
  <pre class="bg-danger">
  Each line for each routes
  Put the follow infos between comma(,):
    <b>local, begin_point, end_point, distance</b>
  </pre>
  <form accept-charset="UTF-8" action="<%=create_massive_paths_path%>" method="get">
    <%= text_area_tag :massive_paths, @info_pattern, rows:15, cols:130 %><br>
    <input name="commit" type="submit" value="Create massive Path">
  </form>
</div>
</div>
<div class="panel panel-default" style="height:250px; overflow:auto;border: solid 1px;">
<div class="panel-body">
<legend>Population</legend>
<table class="table">
  <thead>
    <tr>
      <th>Local</th>
      <th>Begin point</th>
      <th>End point</th>
      <th>Distance (Km)</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.local %></td>
        <td><%= path.begin_point %></td>
        <td><%= path.end_point %></td>
        <td><%= path.distance %></td>
        <td><%= link_to 'Show', path, type:"button", class:"btn btn-info btn-xs" %></td>
        <td><%= link_to 'Edit', edit_path_path(path), type:"button", class:"btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', path, type:"button", class:"btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%#= link_to 'New Path', new_path_path %>
</div>
</div>
<div class="panel panel-default" style="height:350px; overflow:auto;border: solid 1px;">
<div class="panel-body">
<legend>Operation</legend>
  <form>
    <%= text_field_tag :map_id, 'Sampa', type: :text, placeholder: "Local", required:'required'%>
    <%= text_field_tag :begin_point, 'A', type: :text, placeholder: "Begin point", required:'required'%>
    <%= text_field_tag :end_point, 'D', type: :text, placeholder: "End point", required:'required'%>
    <%= text_field_tag :autonomy, '10', type: :text, placeholder: "Autonomy (Km/L)", required:'required'%>
    <%= text_field_tag :price, '2.5', type: :text, placeholder: "Price (R$/L) (ex: 2.5)", required:'required'%>
    <button type="submit" class="btn btn-primary">My route</button>
  </form>
  <div class="alert alert-success" role="alert" style='margin:15px'>
    <p id='top_result'>...</p>
    <h6>Cost(R$), distance(Km) </h6>
  </div>
  <legend>Benchmark</legend>
  <pre id="benchmark">
  </pre>
</div>
</div>
<script>
/*
paths#destroy
GET    /figure/:map_id/:begin_point/:end_point/:autonomy/:pice(.:format) paths#figure
*/
$("form:last").submit(function( event ) {
  $.ajax({
    url: "/figure?"+$('form:last').serialize()
  })
  .done(function(text){})
  .fail(function() {})
  .always(function() {});  
  
  return false;
});
</script>

app/views/paths/new.html.erb
<h1>New path</h1>

<%= render 'form' %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Local:</strong>
  <%= @path.local %>
</p>

<p>
  <strong>Begin point:</strong>
  <%= @path.begin_point %>
</p>

<p>
  <strong>End point:</strong>
  <%= @path.end_point %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @path.distance %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>